#!/usr/bin/env python3
import json
from pathlib import Path
from datetime import datetime, timezone
from copy import deepcopy

BASE_DIR = Path("morph_continuity_pack_v1_4a")
PROJECT_ID = "project_math_lab"

def ts():
    return datetime.now(timezone.utc).isoformat()

def ensure_dir(p: Path):
    p.mkdir(parents=True, exist_ok=True)

def write_json(path: Path, data):
    ensure_dir(path.parent)
    path.write_text(json.dumps(data, indent=2, ensure_ascii=False), encoding="utf-8")

def read_json(path: Path):
    return json.loads(path.read_text(encoding="utf-8"))

def summarize_modules(modules):
    return sorted(set(modules))

CORE_MATH_MODULES = [
    "RuntimeStateManager",
    "ContinuityPackManager",
    "SessionStateAdapter",
    "ComparativeResumeEngine",
    "MergeResolver",
    "AuditTrailEngine",
    "ReplayEngine",
    "IntegrityGuard",
    "FabricOrchestratorV14A",
    "PromptClassifier",
    "TokenDifficultyEstimator",
    "DepthGovernor",
    "MemoryTileManager",
    "RouteMemoryEngine",
    "ResidueRegistry",
    "DeferredWorkRegistry",
    "HorizonPlanner",
    "MultiScaleScheduler",
    "SchedulerPressureEngine",
    "ConflictResolver",
    "QueueArbitrationLayer",
    "CandidateRouteGenerator",
    "BranchScoringLayer",
    "EarlyCollapseController",
    "VerificationTrigger",
]

CORE_SIMPLE_MODULES = CORE_MATH_MODULES[:]

def build_task_record(task_type, route_name, hot_items, modules, verification_armed, avg_depth, usage_count):
    return {
        "task_type": task_type,
        "route_name": route_name,
        "hot_items": hot_items,
        "active_modules": summarize_modules(modules),
        "verification_armed": verification_armed,
        "avg_depth": avg_depth,
        "usage_count": usage_count,
    }

def build_root_session():
    return {
        "project_id": PROJECT_ID,
        "session_id": "session_001",
        "parent_session_id": None,
        "branch_label": "main",
        "saved_at": ts(),
        "budget": {
            "max_depth": 3,
            "verification_threshold": 2,
            "max_hot_items": 3,
            "max_warm_items": 3,
            "force_cold_tail": True,
            "max_candidate_routes": 3,
            "max_residue_bundles_per_task": 5,
            "max_deferred_items_per_task": 12,
            "deferred_trigger_on_medium_normal": True,
            "deferred_trigger_on_deep_normal": True,
        },
        "route_memory": {
            "math": {
                "task_type": "math",
                "run_count": 1,
                "avg_depth": 3.0,
                "verification_rate": 1.0,
                "preferred_hot_items": {
                    "math_simulator": 1,
                    "beal_method": 1,
                    "morph_v05": 1,
                },
                "preferred_modules": {m: 1 for m in CORE_MATH_MODULES},
                "preferred_route_names": {"math_deep_verify": 1},
            },
            "simple": {
                "task_type": "simple",
                "run_count": 1,
                "avg_depth": 1.0,
                "verification_rate": 0.0,
                "preferred_hot_items": {
                    "long_context_notes": 1,
                    "morph_v05": 1,
                    "math_simulator": 1,
                },
                "preferred_modules": {m: 1 for m in CORE_SIMPLE_MODULES},
                "preferred_route_names": {"default_contextual": 1},
            },
        },
        "residue_registry": {
            "math": [
                build_task_record(
                    "math", "math_deep_verify",
                    ["math_simulator", "beal_method", "morph_v05"],
                    CORE_MATH_MODULES, True, 3.0, 1
                )
            ],
            "simple": [
                build_task_record(
                    "simple", "default_contextual",
                    ["long_context_notes", "morph_v05", "math_simulator"],
                    CORE_SIMPLE_MODULES, False, 1.0, 1
                )
            ],
        },
        "deferred_registry": {
            "math": [
                {
                    "task_type": "math",
                    "item_id": "math_deferred_1",
                    "horizon": "deep",
                    "description": "Deferred follow-up generated by v1.4a demo.",
                    "source_route": "math_deep_verify",
                    "source_chunk_index": 0,
                    "priority": 1.0,
                    "reuse_count": 0,
                }
            ]
        },
        "last_fabric_state": {
            "task_type": "math",
            "phase": "complete",
            "chosen_route": "math_deep_verify",
            "verification_armed": True,
            "active_modules": summarize_modules(CORE_MATH_MODULES),
            "health_score": 0.9,
            "historical_route_used": False,
            "residue_bundle_count": 1,
            "depth_history": [3],
            "hot_memory_ids": ["math_simulator", "beal_method", "morph_v05"],
            "warm_memory_ids": ["flux_programming", "morph_v07", "activation_pack"],
            "cold_memory_ids": ["long_context_notes"],
            "horizon_loads": {"immediate": 1, "short": 1, "medium": 1, "deep": 2},
            "deferred_item_count": 1,
            "schedule_loads": {"immediate": 1, "short": 1, "medium": 1, "deep": 2},
            "route_confidence": 0.95,
            "arbitration_count": 1,
        },
        "last_schedule": {
            "immediate_queue": ["route_commit"],
            "short_queue": ["core_claim_pass"],
            "medium_queue": ["structural_consistency_pass"],
            "deep_queue": ["proof_pressure_pass", "route_deepening"],
        },
        "audit_tail": [],
    }

def audit(session, event_type, session_id, branch_label, route_name, outcome, details):
    session["audit_tail"].append({
        "timestamp": ts(),
        "event_type": event_type,
        "project_id": PROJECT_ID,
        "session_id": session_id,
        "branch_label": branch_label,
        "route_name": route_name,
        "outcome": outcome,
        "details": details,
    })
    session["audit_tail"] = session["audit_tail"][-8:]

def save_session(project_dir: Path, session: dict):
    filename = f"{session['session_id']}.json"
    path = project_dir / filename
    write_json(path, session)
    return path

def build_main_continuation(prev):
    s = deepcopy(prev)
    s["session_id"] = "session_002"
    s["parent_session_id"] = "session_001"
    s["branch_label"] = "main"
    s["saved_at"] = ts()
    s["route_memory"]["math"]["run_count"] = 2
    s["route_memory"]["math"]["preferred_hot_items"]["math_simulator"] = 2
    s["route_memory"]["math"]["preferred_hot_items"]["beal_method"] = 2
    s["route_memory"]["math"]["preferred_hot_items"]["morph_v05"] = 2
    for m in s["route_memory"]["math"]["preferred_modules"]:
        s["route_memory"]["math"]["preferred_modules"][m] = 2
    s["route_memory"]["math"]["preferred_route_names"]["math_deep_verify"] = 2
    s["last_fabric_state"]["historical_route_used"] = True
    s["last_fabric_state"]["saved_at"] = ts()
    s["last_fabric_state"]["route_confidence"] = 1.0
    audit(s, "resume_session", "session_002", "main", "math_deep_verify", "loaded", {"path": "session_001.json"})
    return s

def build_fork(prev):
    s = deepcopy(prev)
    s["session_id"] = "session_002__fork_experimental_verify"
    s["parent_session_id"] = "session_002"
    s["branch_label"] = "experimental_verify"
    s["saved_at"] = ts()
    s["deferred_registry"]["math"][0]["reuse_count"] = 1
    audit(s, "fork_session", s["session_id"], s["branch_label"], "math_deep_verify", "forked", {"parent_session_id": "session_002"})
    return s

def build_merge(left, right):
    merged = deepcopy(left)
    merged["session_id"] = "merge__session_002__session_002__fork_experimental_verify"
    merged["parent_session_id"] = "session_002"
    merged["branch_label"] = "merge_main_experimental"
    merged["merge_parents"] = ["session_002", "session_002__fork_experimental_verify"]
    merged["merge_note"] = "Merged main branch with experimental verification branch."
    merged["saved_at"] = ts()
    summary = {
        "left_session_id": left["session_id"],
        "right_session_id": right["session_id"],
        "left_branch_label": left["branch_label"],
        "right_branch_label": right["branch_label"],
        "same_route": True,
        "left_route": "math_deep_verify",
        "right_route": "math_deep_verify",
        "module_overlap_count": len(set(left["last_fabric_state"]["active_modules"]) & set(right["last_fabric_state"]["active_modules"])),
        "left_only_modules": [],
        "right_only_modules": [],
        "left_deferred_count": 1,
        "right_deferred_count": 1,
        "merge_suggestion": "preserve_common_route_and_union_deferred_items",
        "merge_note": "Merged main branch with experimental verification branch.",
        "merged_route": "math_deep_verify",
        "merged_deferred_count": 1,
    }
    merged["merge_summary"] = summary
    audit(merged, "merge_sessions", merged["session_id"], merged["branch_label"], "math_deep_verify", "merged", {
        "left_session_id": left["session_id"],
        "right_session_id": right["session_id"]
    })
    return merged

def session_tree(project_dir: Path):
    ids = [p.stem for p in sorted(project_dir.glob("*.json"))]
    mapping = {}
    for sid in ids:
        data = read_json(project_dir / f"{sid}.json")
        mapping[sid] = {
            "parent_session_id": data.get("parent_session_id"),
            "branch_label": data.get("branch_label"),
            "children": [],
            "merge_parents": data.get("merge_parents", []),
            "merge_note": data.get("merge_note"),
        }
    for sid, info in mapping.items():
        parent = info["parent_session_id"]
        if parent and parent in mapping:
            mapping[parent]["children"].append(sid)
    roots = [sid for sid, info in mapping.items() if info["parent_session_id"] is None]
    return {"sessions": mapping, "roots": roots}

def integrity_report(project_dir: Path):
    problems = []
    files = sorted(project_dir.glob("*.json"))
    ids = set(p.stem for p in files)
    for p in files:
        data = read_json(p)
        parent = data.get("parent_session_id")
        if parent and parent not in ids:
            problems.append({"session_id": p.stem, "missing_parent": parent})
    report = {
        "checked_at": ts(),
        "project_dir": str(project_dir),
        "session_count": len(files),
        "problem_count": len(problems),
        "ok": len(problems) == 0,
        "problems": problems,
        "session_ids": sorted(ids),
    }
    write_json(project_dir / "integrity_report.json", report)
    return report

def replay_snapshot(session):
    snap = {
        "replayed_at": ts(),
        "mode": "branch_replay",
        "project_id": session["project_id"],
        "session_id": session["session_id"],
        "branch_label": session["branch_label"],
        "chosen_route": session["last_fabric_state"]["chosen_route"],
        "verification_armed": session["last_fabric_state"]["verification_armed"],
        "last_phase": session["last_fabric_state"]["phase"],
        "last_schedule": session["last_schedule"],
        "replayed_modules": session["last_fabric_state"]["active_modules"],
        "notes": ["Replay intended for isolated branch validation."],
    }
    write_json(BASE_DIR / PROJECT_ID / "replay_snapshot.json", snap)
    return snap

def main():
    project_dir = BASE_DIR / PROJECT_ID
    ensure_dir(project_dir)

    root = build_root_session()
    p1 = save_session(project_dir, root)

    main2 = build_main_continuation(root)
    p2 = save_session(project_dir, main2)

    fork = build_fork(main2)
    p3 = save_session(project_dir, fork)

    merge = build_merge(main2, fork)
    p4 = save_session(project_dir, merge)

    tree = session_tree(project_dir)
    write_json(project_dir / "session_tree.json", tree)

    report = integrity_report(project_dir)
    replay = replay_snapshot(merge)

    print("=== MORPH Runtime Core v1.4a / Summary ===")
    print(f"Saved root:   {p1}")
    print(f"Saved main:   {p2}")
    print(f"Saved fork:   {p3}")
    print(f"Saved merge:  {p4}")
    print(f"Integrity:    {'ok' if report['ok'] else 'problems'} ({report['problem_count']})")
    print(f"Replay file:  {BASE_DIR / PROJECT_ID / 'replay_snapshot.json'}")
    print("")
    print("=== Quick Snapshot ===")
    print(f"Project:      {PROJECT_ID}")
    print(f"Merge branch: {merge['branch_label']}")
    print(f"Route:        {merge['last_fabric_state']['chosen_route']}")
    print(f"Confidence:   {merge['last_fabric_state']['route_confidence']}")
    print(f"Deferred:     {merge['last_fabric_state']['deferred_item_count']}")
    print(f"Health:       {merge['last_fabric_state']['health_score']}")
    print("")
    print("=== Audit Tail (last events) ===")
    for ev in merge["audit_tail"][-4:]:
        print(f"- {ev['event_type']} | {ev['outcome']} | {ev['session_id']}")

if __name__ == "__main__":
    main()
